config/routes.rb
Rails.application.routes.draw do
  resources :espacos
  resources :funcionarios
  resources :clientes
  resources :veiculos
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :veiculos
  get 'home/index'
  get 'wellcome/index'
  get 'wellcome/sair'
  get 'wellcome/entrar'
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root 'wellcome#index', as: :authenticated_root
  end


  root 'home#index'
  #root '/users/sign_in'


end

app/controllers/wellcome_controller.rb
class WellcomeController < ApplicationController

  before_action :authenticate_user!

  def index

    @user = current_user

    if params[:search]
      @aux = Cliente.where("Nome like ?", "%#{params[:search]}%")
    else
      @aux = Cliente.all
    end

    if @user.role == 1
      redirect_to admin_path
    end
    
    @aux.each do |item|
      if item.user_id == @user.id
        @cliente = item
        if item.user.role == 1
          
          @tempo = item.veiculo.Saida - item.veiculo.Entrada
        end
      end
    end

    @espaco = Espaco.first

  end

  def sair

    @cliente = Cliente.find(params[:client_id])

    @cliente.veiculo.Estacionado = false

    @cliente.veiculo.Saida = Time.now

    @esta = Espaco.first

    @esta.Vagas = @esta.Vagas + 1

    tempo = (@cliente.veiculo.Saida - @cliente.veiculo.Entrada)/3600

    tempo = tempo.to_i

    @cliente.Horas = @cliente.Horas - tempo

    @esta.save

    @cliente.save

    redirect_to root_path
    
  end
  
  def entrar

    @cliente = Cliente.find(params[:client_id])

    @cliente.veiculo.Estacionado = true

    @cliente.veiculo.Entrada = Time.now

    @esta = Espaco.first

    if @esta.Vagas > 0 && @cliente.Horas > 0
      
      @esta.Vagas = @esta.Vagas - 1
      
      @esta.save
      
      @cliente.save
      
      redirect_to root_path
    
    else
    
      flash[:notice] = "Operação Inválida"

      redirect_to root_path

    end
    
  end

end

app/helpers/wellcome_helper.rb
module WellcomeHelper
end

app/views/wellcome/index.html.erb
<div class="container w-75" >  
  <div class="mt-5 text-center px-5 pb-3 shadow-lg rounded" style="background: linear-gradient(#009999, #000066)">

    <br>

    <% if policy(@user).index? == false %>
      <h1 class="text-left"><%=  "Welcome #{@cliente.Nome}" %></h1>

        <div class="h3">
          <br>
          <%= "Horas disponíveis: #{@cliente.Horas}"%><br>
          <%= "Plano: #{@cliente.Plano}"%>
        </div>

        <div class="text-right">
          <%= link_to  "Log out", destroy_user_session_path, method: :delete  %><br>
          <%= link_to 'Editar Perfil', edit_cliente_path(@cliente) %><br>
          <%= link_to 'Apagar Conta', @cliente, method: :delete, data: { confirm: 'Você realmente quer apagar essa conta?' } %><br>
        </div>

    <% else %>     

      <h1><%=  "Welcome" %></h1>

      <br>
      <br>
      <div class="text-left">
      <%= form_tag(root_path, :method => :get) do %>
        <%= text_field_tag 'search', nil, placeholder: 'Nome do Cliente' %>
        <%= submit_tag "Search" %>
      <% end %>
      </div>
      <br>

      <table class="table table-striped table-dark">
        <thead>
          <tr>
            <th scope="col">Nome</th>
            <th scope="col">Idade</th>
            <th scope="col">Cpf</th>
            <th scope="col">Sexo</th>
            <th scope="col">Plano</th>
            <th scope="col">Horas</th>
            <th scope="col">Veiculo</th>
            <th scope="col">User</th>
            <th scope="col">Ação</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @aux.each do |cliente| %>
            <tr>

              <th scope="row"><%= cliente.Nome %></th>
              <td><%= cliente.Idade %></td>
              <td><%= cliente.Cpf %></td>
              <td><%= cliente.Sexo %></td>
              <td><%= cliente.Plano %></td>
              <td><%= cliente.Horas %></td>
              <td><%= cliente.veiculo.Modelo %></td>
              <td><%= cliente.user.email %></td>
              <td>
              <% if cliente.veiculo.Estacionado? %>

                <%= link_to 'Sair', wellcome_sair_path(:client_id => cliente.id ) %>           
              
              <% else %>

                <%= link_to 'Entrar', wellcome_entrar_path(:client_id => cliente.id ) %> 

              <%end%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <h2><%= "Vagas: #{@espaco.Vagas}" %></h2>

      <br>

      <h2 class="text-right"><%= link_to  "Log out", destroy_user_session_path, method: :delete %></h2>
    
    <% end %>

  </div>
</div>