config/routes.rb
Rails.application.routes.draw do
  resources :espacos
  resources :funcionarios
  resources :clientes
  resources :veiculos
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :veiculos
  get 'home/index'
  get 'wellcome/index'
  get 'wellcome/sair'
  get 'wellcome/entrar'
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root 'wellcome#index', as: :authenticated_root
  end


  root 'home#index'
  #root '/users/sign_in'


end

app/models/espaco.rb
class Espaco < ApplicationRecord
end

app/controllers/espacos_controller.rb
class EspacosController < ApplicationController
  before_action :set_espaco, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /espacos
  # GET /espacos.json
  def index
    @espacos = Espaco.all

    @users = User.all
    authorize @users
  end

  # GET /espacos/1
  # GET /espacos/1.json
  def show
  end

  # GET /espacos/new
  def new
    @espaco = Espaco.new
  end

  # GET /espacos/1/edit
  def edit
  end

  # POST /espacos
  # POST /espacos.json
  def create
    @espaco = Espaco.new(espaco_params)

    respond_to do |format|
      if @espaco.save
        format.html { redirect_to @espaco, notice: 'Espaco was successfully created.' }
        format.json { render :show, status: :created, location: @espaco }
      else
        format.html { render :new }
        format.json { render json: @espaco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /espacos/1
  # PATCH/PUT /espacos/1.json
  def update
    respond_to do |format|
      if @espaco.update(espaco_params)
        format.html { redirect_to @espaco, notice: 'Espaco was successfully updated.' }
        format.json { render :show, status: :ok, location: @espaco }
      else
        format.html { render :edit }
        format.json { render json: @espaco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /espacos/1
  # DELETE /espacos/1.json
  def destroy
    @espaco.destroy
    respond_to do |format|
      format.html { redirect_to espacos_url, notice: 'Espaco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_espaco
      @espaco = Espaco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def espaco_params
      params.require(:espaco).permit(:Vagas, :Valor_Hora)
    end
end

app/helpers/espacos_helper.rb
module EspacosHelper
end

app/views/espacos/_form.html.erb
<%= form_with(model: espaco, local: true) do |form| %>
  <% if espaco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(espaco.errors.count, "error") %> prohibited this espaco from being saved:</h2>

      <ul>
      <% espaco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Vagas %>
    <%= form.number_field :Vagas %>
  </div>

  <div class="field">
    <%= form.label :Valor_Hora %>
    <%= form.text_field :Valor_Hora %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/espacos/edit.html.erb
<h1>Editing Espaco</h1>

<%= render 'form', espaco: @espaco %>

<%= link_to 'Show', @espaco %> |
<%= link_to 'Back', espacos_path %>

app/views/espacos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Espacos</h1>

<table>
  <thead>
    <tr>
      <th>Vagas</th>
      <th>Valor hora</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @espacos.each do |espaco| %>
      <tr>
        <td><%= espaco.Vagas %></td>
        <td><%= espaco.Valor_Hora %></td>
        <td><%= link_to 'Show', espaco %></td>
        <td><%= link_to 'Edit', edit_espaco_path(espaco) %></td>
        <td><%= link_to 'Destroy', espaco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Espaco', new_espaco_path %>

app/views/espacos/new.html.erb
<h1>New Espaco</h1>

<%= render 'form', espaco: @espaco %>

<%= link_to 'Back', espacos_path %>

app/views/espacos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vagas:</strong>
  <%= @espaco.Vagas %>
</p>

<p>
  <strong>Valor hora:</strong>
  <%= @espaco.Valor_Hora %>
</p>

<%= link_to 'Edit', edit_espaco_path(@espaco) %> |
<%= link_to 'Back', espacos_path %>