config/routes.rb
Rails.application.routes.draw do
  resources :espacos
  resources :funcionarios
  resources :clientes
  resources :veiculos
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :veiculos
  get 'home/index'
  get 'wellcome/index'
  get 'wellcome/sair'
  get 'wellcome/entrar'
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root 'wellcome#index', as: :authenticated_root
  end


  root 'home#index'
  #root '/users/sign_in'


end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  belongs_to :user
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all

    @users = User.all
    authorize @users
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:Nome, :Idade, :Cpf, :Sexo, :Carros_Registrados, :Salario, :Carga_Horaria, :user_id)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario, local: true) do |form| %>
  <% if funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% funcionario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :Nome %>
  </div>

  <div class="field">
    <%= form.label :Idade %>
    <%= form.number_field :Idade %>
  </div>

  <div class="field">
    <%= form.label :Cpf %>
    <%= form.text_field :Cpf %>
  </div>

  <div class="field">
    <%= form.label :Sexo %>
    <%= form.text_field :Sexo %>
  </div>

  <div class="field">
    <%= form.label :Carros_Registrados %>
    <%= form.number_field :Carros_Registrados %>
  </div>

  <div class="field">
    <%= form.label :Salario %>
    <%= form.text_field :Salario %>
  </div>

  <div class="field">
    <%= form.label :Carga_Horaria %>
    <%= form.number_field :Carga_Horaria %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editing Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Show', @funcionario %> |
<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Funcionarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Cpf</th>
      <th>Sexo</th>
      <th>Carros registrados</th>
      <th>Salario</th>
      <th>Carga horaria</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.Nome %></td>
        <td><%= funcionario.Idade %></td>
        <td><%= funcionario.Cpf %></td>
        <td><%= funcionario.Sexo %></td>
        <td><%= funcionario.Carros_Registrados %></td>
        <td><%= funcionario.Salario %></td>
        <td><%= funcionario.Carga_Horaria %></td>
        <td><%= funcionario.user %></td>
        <td><%= link_to 'Show', funcionario %></td>
        <td><%= link_to 'Edit', edit_funcionario_path(funcionario) %></td>
        <td><%= link_to 'Destroy', funcionario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funcionario', new_funcionario_path %>

app/views/funcionarios/new.html.erb
<h1>New Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.Nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @funcionario.Idade %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @funcionario.Cpf %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @funcionario.Sexo %>
</p>

<p>
  <strong>Carros registrados:</strong>
  <%= @funcionario.Carros_Registrados %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @funcionario.Salario %>
</p>

<p>
  <strong>Carga horaria:</strong>
  <%= @funcionario.Carga_Horaria %>
</p>

<p>
  <strong>User:</strong>
  <%= @funcionario.user %>
</p>

<%= link_to 'Edit', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Back', funcionarios_path %>